<a href="https://colab.research.google.com/github/Harithamuralidharan/Financial-Risk-for-Loan-Approval/blob/main/Financial_Risk_for_Loan_Approval_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Financial Risk for Loan Approval

##Introduction

---
 This study explores the different types of financial risks involved in loan approvals, the methods used to assess these risks, and strategies for minimizing defaults while maintaining a balance between profitability and accessibility. To evaluating the model and understanding these risks is crucial for both lenders and borrowers in making informed financial decisions.

##CONTENTS

---

---



1.Information about the Project

---

2.Import the Libraries

---
3.Injuct Data

---

###Informaition about the Project


---
The financial sector is witnessing a paradigm shift in risk assessment strategies due to evolving economic conditions, regulatory changes, and technological advancements. This project focuses on developing a comprehensive risk assessment framework for loan approval by analyzing key financial and personal attributes of applicants. The goal is to enhance decision-making, minimize default risks, and optimize lending strategies in an increasingly competitive market.



####Practical Relevanc and industry Significance

1.Economic Volatility & Rising Loan Defaults

*   A robust risk assessment system can help predict and mitigate potential losses, ensuring financial stability.

2.Regulatory Compliance & Risk Management


*  Developing a data-driven risk model helps financial institutions remain compliant while ensuring responsible lending.

3.Technological Innovations in Credit Risk Assessment


*   Traditional credit scores fail to capture holistic borrower profiles.

*   Machine learning, AI, and alternative data sources (such as utility bill payments, employment stability, and financial habits) can improve loan approval accuracy.

4.Market Competition & Digital Transformation



*   Institutions that leverage advanced risk analytics can offer faster approvals, personalized interest rates, and reduced default rates, gaining a competitive advantage.



####Project Goals
Develop a predictive model to assess financial risk and loan approval likelihood.
Identify key financial indicators that influence loan approval decisions.
Enhance risk mitigation strategies for lenders.
Ensure fairness in lending decisions by incorporating diverse borrower attributes.

####The dataset includes the following columns:


---

1.Age : Applicant's age

2.AnnualIncome : Yearly income

3.CreditScore : Creditworthiness score

4.EmploymentStatus : Job situation

5.EducationLevel : Highest education attained

6.Experience : Work experience

7.LoanAmount : Requested loan size

8.LoanDuration : Loan repayment period

9.MaritalStatus : Applicant's marital state

10.NumberOfDependents : Number of dependents

11.HomeOwnershipStatus : Homeownership type

12.MonthlyDebtPayments : Monthly debt obligations

13.CreditCardUtilizationRate : Credit card usage percentage

14.NumberOfOpenCreditLines : Active credit lines

15.NumberOfCreditInquiries : Credit checks count

16.DebtToIncomeRatio : Debt to income proportion

17.BankruptcyHistory : Bankruptcy records

18.LoanPurpose : Reason for loan

19.PreviousLoanDefaults : Prior loan defaults

20.PaymentHistory : Past payment behavior

21.LengthOfCreditHistory : Credit history duration

22.SavingsAccountBalance : Savings account amount

23.CheckingAccountBalance : Checking account funds

24.TotalAssets : Total owned assets

25.TotalLiabilities : Total owed debts

26.MonthlyIncome : Income per month

27.UtilityBillsPaymentHistory : Utility payment record

28.JobTenure : Job duration

29.NetWorth : Total financial worth

30.BaseInterestRate : Starting interest rate

31.InterestRate : Applied interest rate

32.MonthlyLoanPayment : Monthly loan payment

33.TotalDebtToIncomeRatio : Total debt against income

34.LoanApproved : Loan approval status

35.RiskScore : Risk assessment score

##2.Import the Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

##3.Injuct Data

In [ ]:
data = pd.read_csv("Loan.csv")
data.head(5)

,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,NumberOfDependents,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,45.0,39948.0,617.0,Employed,Master,22.0,13152.0,48.0,Married,2.0,...,3329.000000,0.724972,11.0,NaN,0.199652,0.227590,419.805992,0.181077,0,49.0
1,38.0,39709.0,628.0,Employed,Associate,15.0,26045.0,48.0,Single,1.0,...,3309.083333,0.935132,3.0,43609.0,0.207045,0.201077,794.054238,NaN,0,52.0
2,47.0,40724.0,570.0,Employed,Bachelor,26.0,17627.0,36.0,Married,2.0,...,3393.666667,0.872241,6.0,5205.0,0.217627,NaN,666.406688,0.462157,0,52.0
3,58.0,69084.0,545.0,Employed,High School,34.0,37898.0,96.0,Single,1.0,...,5757.000000,0.896155,5.0,99452.0,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,37.0,103264.0,594.0,Employed,Associate,17.0,9184.0,36.0,Married,1.0,...,8605.333333,0.941369,5.0,227019.0,0.197184,0.175990,330.179141,0.070210,1,36.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         19989 non-null  float64
 1   AnnualIncome                19998 non-null  float64
 2   CreditScore                 19996 non-null  float64
 3   EmploymentStatus            19996 non-null  object
 4   EducationLevel              19999 non-null  object
 5   Experience                  19997 non-null  float64
 6   LoanAmount                  19995 non-null  float64
 7   LoanDuration                19989 non-null  float64
 8   MaritalStatus               19994 non-null  object
 9   NumberOfDependents          19997 non-null  float64
 10  HomeOwnershipStatus         19994 non-null  object
 11  MonthlyDebtPayments         19989 non-null  float64
 12  CreditCardUtilizationRate   19990 non-null  float64
 13  NumberOfOpenCreditLines     19996 non-null  float64
 14  NumberOfCreditInquiries     20000 non-null  int64
 15  DebtToIncomeRatio           19997 non-null  float64
 16  BankruptcyHistory           19999 non-null  float64
 17  LoanPurpose                 19991 non-null  object
 18  PreviousLoanDefaults        19991 non-null  float64
 19  PaymentHistory              19995 non-null  float64
 20  LengthOfCreditHistory       19997 non-null  float64
 21  SavingsAccountBalance       19993 non-null  float64
 22  CheckingAccountBalance      19994 non-null  float64
 23  TotalAssets                 19993 non-null  float64
 24  TotalLiabilities            19995 non-null  float64
 25  MonthlyIncome               19997 non-null  float64
 26  UtilityBillsPaymentHistory  19996 non-null  float64
 27  JobTenure                   19998 non-null  float64
 28  NetWorth                    19999 non-null  float64
 29  BaseInterestRate            19999 non-null  float64
 30  InterestRate                19997 non-null  float64
 31  MonthlyLoanPayment          20000 non-null  float64
 32  TotalDebtToIncomeRatio      19999 non-null  float64
 33  LoanApproved                20000 non-null  int64
 34  RiskScore                   20000 non-null  float64
dtypes: float64(28), int64(2), object(5)
memory usage: 5.3+ MB

In [ ]:
data.shape

(20000, 35)